# Generated by Django 5.2 on 2025-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_product_departure_date_product_departure_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
